"use strict";

const fs = require("fs");
const feather = require("feather-icons");
const { exec } = require("child_process");
const featherMappings = require("./feather-mappings.json");

let icons = [],
  replacers = [];
const prefix = "ft-";
const componentName = "feather-icons";

// LOOP THROUGH FEATHER ICONS
for (const discourseIconId in featherMappings) {
  const iconId = featherMappings[discourseIconId];

  let svg = `
    <symbol id="${prefix}${iconId}">
      ${feather.icons[iconId].toSvg()}
    </symbol>
  `;

  svg = svg.replace('width="24" ', "");
  svg = svg.replace('height="24" ', "");

  if (!icons.includes(svg)) {
    icons.push(svg);
  }
  replacers.push(
    `api.replaceIcon("${discourseIconId}", "${prefix}${iconId}");`
  );
}

// GENERATE SPRITE
const sprite = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  ${icons.join("\n")}
</svg>
`;

fs.writeFile(
  `repos/discourse-${componentName}/assets/icons-sprite.svg`,
  sprite,
  (err) => {
    if (err) {
      console.error(err);
      return;
    }

    console.log("Success! Icon sprite was updated.");
  }
);

// GENERATE DISCOURSE JS INITIALIZER
const jsContent = `// autogenerated via "yarn run build.js"
import { withPluginApi } from "discourse/lib/plugin-api";

function initIcons(api) {
  ${replacers.join("\n  ")}
}

export default {
  name: "${componentName}",
  initialize() {
    withPluginApi("0.10.1", initIcons);
  },
};

`;

fs.writeFile(
  `repos/discourse-${componentName}/javascripts/discourse/initializers/${componentName}.js.es6`,
  jsContent,
  (err) => {
    if (err) {
      console.error(err);
      return;
    }

    console.log("Success! Javascript initializer was updated.");
  }
);

// GENERATE COMPONENT ABOUT.JSON FILE

const aboutContent = `{
  "name": "discourse-${componentName}",
  "description": "Feather icons for Discourse",
  "about_url": null,
  "license_url": null,
  "component": true,
  "assets": {
    "icons-sprite": "/assets/icons-sprite.svg"
  }
}
`;

fs.writeFile(
  `repos/discourse-${componentName}/about.json`,
  aboutContent,
  (err) => {
    if (err) {
      console.error(err);
      return;
    }

    console.log("Success! About file was updated.");
  }
);

exec("ls -la", (error, stdout) => {
  console.log(`stdout: ${stdout}`);
});
